services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.2
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql # ✅ must match the service name of your MySQL container
      PMA_USER: root # Optional, for convenience
      PMA_PASSWORD: mypassword # Optional, matches MYSQL_ROOT_PASSWORD

volumes:
  mysql_data:
